name: daniel-grupo

services:
  php:
    container_name: daniel-grupo-php
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: daniel-grupo/php:8.3
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-8000}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - daniel-grupo

  mysql:
    container_name: daniel-grupo-mysql
    image: mysql:8.4
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-cruznegra}'
      MYSQL_USER: '${DB_USERNAME:-sail}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
    volumes:
      - daniel-grupo-mysql-data:/var/lib/mysql
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD:-password}']
      retries: 5
      timeout: 5s
      interval: 5s
    networks:
      - daniel-grupo

networks:
  daniel-grupo:
    name: daniel-grupo-network
    driver: bridge

volumes:
  daniel-grupo-mysql-data:
    name: daniel-grupo-mysql-data
